packages:
  - packages/*

catalog:
  "@types/node": "^22.7.4"
  "@types/react": "^18.3.10"
  "@types/react-dom": "^18.3.0"
  "react": "^18.3.1"
  "react-dom": "^18.3.1"

  "@vitejs/plugin-react-swc": "^3.7.0"
  "typescript": "^5.6.3"
  "typescript-eslint": "^8.13.0"
  "vite": "^5.4.8"
